### ISSUE TITLE
Cannot use module in basic Expo app

### ISSUE THREAD

**Issue by Sejmou** [motiz88/react-native-midi#14]
Hello,

I wanted to test this module in a basic Expo app created via `npx create-expo-app -t expo-template-blank-typescript`. After getting the basic starter app running, I ran `expo install @motiz88/react-native-midi` as suggested in the README. This command did not produce any errors. However, once I try to use the module in my code, it fails (both for iOS and Android).

Here's the code I use in `App.tsx`:

```ts
import { StatusBar } from 'expo-status-bar';
import { StyleSheet, Text, View } from 'react-native';
import { requestMIDIAccess } from '@motiz88/react-native-midi';
import { useEffect } from 'react';

export default function App() {
  useEffect(() => {
    requestMIDIAccess().then(midiAccess => {
      // Use midiAccess.inputs and midiAccess.outputs
      console.log(midiAccess.inputs);
    });
  }, []);
  console.log('hello');
  return (
    <View style={styles.container}>
      <Text>Open up App.js to start working on your app!</Text>
      <StatusBar style="auto" />
    </View>
  );
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#fff',
    alignItems: 'center',
    justifyContent: 'center',
  },
});
```

The error I get (both for `npm run ios` and `npm run android` is
```
 ERROR  Error: Cannot find native module 'ReactNativeMidi', js engine: hermes
 ERROR  Invariant Violation: "main" has not been registered. This can happen if:
* Metro (the local dev server) is run from the wrong folder. Check if Metro is running, stop it and restart it in the current project.
* A module failed to load due to an error and `AppRegistry.registerComponent` wasn't called., js engine: hermes
```

What could I be doing wrong?

**Comment by motiz88** [comment]
Hey @Sejmou! The error means you haven't updated the native part of your app after installing the module. Try `npx expo prebuild` to automatically update your iOS and Android project files, followed by `npx expo run:ios` or `npx expo run:android` to build and launch the app on your device.
