### ISSUE TITLE
`MIDIInput.onmidimessage` doesn't get updated React State values

### ISSUE THREAD

**Issue by kimchouard** [motiz88/react-native-midi#7]
When I assign a function to `MIDIInput.onmidimessage`, the state variables within it doesn't get updated after calling `setXxx()`. 

🤦🏼‍♂️ Not sure if I'm missing something in my React Hooks or if there's a real issue, but would love your insights here. 🙏

## Code Details

I have `noteOn` and `noteOff` state variables :
```javascript
  const [noteOn, setNoteOn] = useState(null);
  const [noteOff, setNoteOff] = useState(null);
```

I also have a `startMIDI()` function, that's binding a function to `MIDIInput.onmidimessage` :
```javascript
const startMIDI = () => {
  requestMIDIAccess().then((tempMIDIAccess) => {
    tempMIDIAccess?.inputs.forEach((MIDIInput) => {
      if (MIDIInput?.deviceInfo?.properties?.name.search('TravelSax2') !== -1) {
        // Binding a function to MIDIInput.onmidimessage
        MIDIInput.onmidimessage = (event: MIDIMessageEvent) => {
          const command = event.data[0];
          const MIDINote = event.data[1];

          switch (command) {
            case 144: // noteOn
              setNoteOn(MIDINote);

              console.log('noteOn : ', MIDINote);
              break;
            case 128: // noteOff
              setNoteOff(MIDINote);

              // This console log will return null for `noteOn` although it's been assigned before.
              console.log('noteOff : ', MIDINote, ' with noteOn = ', noteOn);
              break;
            default:
              console.error('Command code not found for :', command);
              break;
          }
        };
      }
    });
  });
};
```

Okay now, say I play a C note and stop : 
1. `setNoteOn()` is triggered and sets `noteOn` to the C note MIDI value
2. When I stop playing the note, the `console.log` in the switch case `128` return a `null` value for `noteOn` although it's been assigned before, as if it's been keeping the `noteOn` state value from when `MIDIInput.onmidimessage` was assigned... 🤔

FYI, here's where I'm calling `startMIDI()`, controlled by a `MIDIOn` boolean param on my component allowing to turn it on and off:
```javascript

  // Mounting App
  useEffect(() => {
    console.log('Mounting MIDIMAnager. On: ', MIDIOn, ' SaxConnected: ', isSaxMIDIConnected);

    // Starting the MIDI Connection when turned on
    if (MIDIOn === true) {
      startMIDI();
    }

    // Disconnect if MIDI turned off
    if (MIDIOn === false) {
      stopMIDI();
    }

    // When UNMOUNTING App
    return () => {
      console.log('Unmounting MIDIManager');
      stopMIDI();
    };
  }, [MIDIOn]);
```

Any thoughts ? 🤨

**Comment by kimchouard** [comment]
Alright, I found a fix. It seems like the `MIDIInput.onmidimessage` required a `useRef` value to have the most up to date value.

Update the noteOn assignment to (and same for noteOff):
```javascript
const [noteOn, setStateNoteOn] = useState(null);
const noteOnRef = useRef(noteOn);
const setNoteOn = (note) => {
  noteOnRef.current = note;
  setStateNoteOn(note);
};
```

Then, you'll get the right `noteOn` value using the ref, `noteOnRef.current`. In our example, for the console log:
```javascript
console.log('noteOff : ', noteObj.MIDINumber, ' with noteOn = ', noteOnRef?.current?.MIDINumber);
```

@motiz88 would you agree with this fix? If yes, I can write a note for the README to help the next ones using the lib. :)

**Comment by motiz88** [comment]
Hey @kimchouard - I suspect this is more an issue with the way you're using hooks (e.g. missing dependencies) than an issue with the library. For example, in your initial code snippet, `startMIDI` appears to be a function in local scope (it has access to `setNoteOn` etc) but your `useEffect` call doesn't include `startMIDI` as a dependency. Are you using the `rules-of-hooks` ESLint rule in your project?

Happy to keep trying to help but closing this issue as there isn't anything to do here from a library perspective.
